server:
  port: 8080

spring:
  application:
    name: sso-service
  redis:
    database: 0
    host: 69.230.196.65
    port: 26379
    lettuce:
      pool:
        max-active: 8
        max-idle: 5
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 6000
    timeout: 60000
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML

jwt:
  secret: 123456